### ISSUE TITLE
Take inspiration from Learnable Programming

### ISSUE THREAD

**Issue by greggman** [greggman/threejsfundamentals#9]
There's a great article [Learnable Programming](http://worrydream.com/#!/LearnableProgramming) with crazy ideas for learning to program

Of course this site is not about learning to program it's about already knowing how to program and learning how to use a library, three.js

Still, I wondered what if any idea we can take and or more importantly *should* take.

I recently added code snippets to [the primitives article](https://threejsfundamentals.org/threejs/lessons/threejs-primitives.html) and when I started my original goal was I was going to make it so if you clicked on a number a range slider would appear letting you change the inputs.

It's a neat idea but i wasn't sure it was good idea, nor was I sure it was worth my time (as in spend 1-5 hours adding the sliders or spend 1-5 hours working on the next article)

In any case the idea was to add parsable comments like

```
const width = 8;   // ui:range min: 0, max: 10
const height = 8;  // ui:range min: 0, max: 10
const depth = 8;  // ui:range min: 0, max: 10
const geometry = THREE.BoxBufferGeometry(width, height, depth);
```

Then parse the comments , find the number on the line and generate a slider that only appears on click/hover. If there are multiple numbers the use multiple comments or some separate or whatever, that's not important.

What hit me was also how many parameters I left out. For example `CircleBufferGeometry` as the start and end settings. I think it would be more confusing to show a sample that uses all the settings since you can't tell what's optional. I suppose I could add multiple examples, `CircleBufferGeometry` using 2 args and again with 4. That might be important to do regardless of adding fancy interactivity.

Anyway, that made me wonder rather than sliders I should just make the code live. Turn each code block into an editor. A little worried about how much memory it would use I think it's back to whether any of this is a good or bad idea vs just a cool idea. The geek in me wants to add one or both because it's "cool" but another part of me feels like it's a huge waste of time and other than 1 out of 1000 visitors touching it and going "Wow, Cool" it's not useful.

Still, if there are any other ideas from that article or anyone else has I'm open to suggestions.

**Comment by NikitaIT** [comment]
# Existing
Analyze these interactive resources based on the article Learnable Programming:
- https://refactoring.guru/
- https://stepik.org/course/579
- http://jqfundamentals.com/ (click on icon-eye-open)
- https://www.codecademy.com/learn
- https://htmlacademy.ru/courses
- http://pythontutor.ru/

I'm sorry that most resources in list is ru, but you can also watch them with a translator)

They have one common problem - they come up with private solutions to common problems.
1. watch, ask, learn from them experience
2. reuse existing solutions

# You want to add a new "button" to the site that does something new.
Sounds easy.
Why do you spend 1-5 hours? Why not ask those who have already added this button, how to add it. Yes, you will spend 5 hours to learn how to do it, but the implementation will take much less time.

# You want to do an interactive course
The best way is to make a course about "how to do an interactive course", 
this way you kill two birds with one stone, spend time on a new article and add interactivity that can be quickly and easily reused in other courses. 

You already did it! For example, in the article about a lot of canvases on the page.

I remember reading in [Dive into html](http://diveinto.html5doctor.com/) what paper books should give way to this new web format. Since that time, the web format has become incredibly popular, but good free tools and platforms have not yet appeared and all make crutches. And you want to make crutches, too.

# you describe in too much detail what is already written in the code
Look at https://refactoring.guru/ there there is writing code on steps, in one-year window editor slightly better than here http://threejsplaygnd.brangerbriz.net/gui/ 

**this is a very important link http://threejsplaygnd.brangerbriz.net/gui/ all clear without words**
